export const data = [
    {
        id: 1,
        producto: "Remera",
        imagen: [],
        stock: 10,
        precio: 1500,
        categoria:"indumentaria",
    },
    {
        producto: "Pantalon",
        id: 2,
        imagen: [],
        stock: 6,
        precio: 1700,
        categoria:"indumentaria",
    },
    {
        producto: "Campera",
        id: 3,
        imagen: [],
        stock: 0,
        precio: 2200,
        categoria:"indumentaria",
    },
    {
        producto: "Buzo",
        id: 4,
        imagen: [],
        stock: 7,
        precio: 2100,
        categoria:"indumentaria",
    },
    {
        producto: "Cinturon",
        id: 5,
        imagen: [],
        stock: 12,
        precio: 800,
        categoria:"indumentaria",
    },
    {
        producto: "Medias",
        id: 6,
        imagen: [],
        stock: 0,
        precio: 450,
        categoria:"indumentaria",
    },
    {
        producto: "Zapatillas Running",
        id: 7,
        imagen: [],
        stock: 3,
        precio: 9050,
        categoria:"calzado",
    },
    {
        producto: "Zapatillas de vestir",
        id: 8,
        imagen: [],
        stock: 0,
        precio: 450,
        categoria:"calzado",
    },
    {
        producto: "Zapatos",
        id: 9,
        imagen: [],
        stock: 5,
        precio: 10250,
        categoria:"calzado",
    },
    {
        producto: "Botines",
        id: 10,
        imagen: [],
        stock: 2,
        precio: 9450,
        categoria:"calzado",
    },
    {
        producto: "Tacos",
        id: 11,
        imagen: [],
        stock: 1,
        precio: 10450,
        categoria:"calzado",
    },
    {
        producto: "Crocs",
        id: 12,
        imagen: [],
        stock: 5,
        precio: 4450,
        categoria:"calzado",
    },
]